### ISSUE TITLE
after upload api , a new undefined folder is been getting created

### ISSUE THREAD

**Issue by pavanpsanu** [Chiff/ng6-file-man-express#5]
after uploading any file , a new folder is getting automatically created (named as undefined) , pls solve this issue , 
if possible please provide a code (backend and frontend ) for view api aswell 
![before upload pic of folder](https://user-images.githubusercontent.com/41718223/123923093-4b88ff00-d9a6-11eb-9975-8b60a3aba17e.PNG)
![uploaded successfully](https://user-images.githubusercontent.com/41718223/123923114-517ee000-d9a6-11eb-8947-318c5ac54dfb.PNG)
![after upload undefined folder is been created](https://user-images.githubusercontent.com/41718223/123923143-593e8480-d9a6-11eb-8499-d8e2ba97afa5.PNG)

**Comment by Chiff** [comment]
Fixed with d73370086468465594a6d200f5bbaf44703e43ff , however, this API is not meant to be used in a real environment. It is just an example of a "working" API for `ng6-file-man` you can surely use it but it is very limited.

If you have any improvements, pull requests are welcomed.
